[package]
name = "halo2-snark-aggregator"
version = "0.1.0"
edition = "2021"
authors = ["zhangjunyu <junyu92@gmail.com>"]

[dependencies]
blake2b_simd = "1"
cfg-if = "0.1"
chrono = "0.4.19"
group = "0.11"
halo2_proofs = { path = "../halo2/halo2_proofs", default-features = true }
num-bigint = { version = "0.4", features = ["rand"] }
num-integer = "0.1"
num-traits = "0.2"
pairing_bn256 = { git = "https://github.com/appliedzkp/pairing" }
poseidon = { git = "https://github.com/appliedzkp/poseidon.git", branch = "circuit" }
rand = "0.8"
rand_core = "0.6"
rand_pcg = "0.3.1"
rand_xorshift = "0.3"
subtle = "2.3"

[features]
default = ["halo2"]
blake2b = []
halo2 = []
plonk = []
